tap thoughtbot/formulae
install ansible
install ant
install awscli
install bash
install caskroom/cask/brew-cask
install cmake
install homebrew/fuse/encfs
install fig
install fwknop
install git
install git-extras
install gnupg
install htop-osx
install icu4c
install ipcalc
install jq
install libpqxx
install ncdu
install nmap
install ossp-uuid
install packer
install pgcli
install polipo
install postgresql
install pwgen
install python
install rbenv-gem-rehash
install thoughtbot/formulae/rcm
install ruby-build
install siege
install giantswarm/swarm/swarm-client
install terraform
install the_silver_searcher
install tig
install tmux
install tree
install vim
install watch
install wget
