[tools]
chezmoi = "latest"
clusterctl = "latest"
cosign = "latest"
go = "latest"
goreleaser = "latest"
helm = "latest"
helmfile = "latest"
kops = "latest"
kubectl = "1.33.5"
node = "latest"
npm = "latest"
opentofu = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
shellcheck = "latest"
slsa-verifier = "latest"
terraform = "latest"
trivy = "latest"

[tasks.reset]
description = 'Reset .kube/config'
run = "git checkout . && chmod 600 config"
dir = "/Users/kai/.kube"
alias = 'r' # `mise run r`
