# /Users/kforsthoevel/.config/tmuxinator/aws.yml

name: aws
root: ~/git

windows:
  - core:
      root: ~/git/aws-terraform/eu-west-1/core
      layout: even-vertical
      panes:
        - vim
        - clear
  - staging:
      root: ~/git/aws-terraform/eu-west-1/staging
      layout: even-vertical
      panes:
        - vim
        - clear
  - production:
      root: ~/git/aws-terraform/eu-west-1/production
      layout: even-vertical
      panes:
        - vim
        - clear
  - infra:
      root: ~/git/aws-terraform/eu-west-1/infra
      layout: even-vertical
      panes:
        - vim
        - clear
  - s3:
      root: ~/git/aws-terraform/eu-west-1/s3
      layout: even-vertical
      panes:
        - vim
        - clear
