# /Users/kforsthoevel/.config/tmuxinator/aws.yml

name: aws
root: ~/git/aws-terraform

windows:
  - eu-west-1:
      root: ~/git/aws-terraform/eu-west-1
      layout: even-vertical
      panes:
        - nvim
        -
  - us-east-1:
      root: ~/git/aws-terraform/us-east-1
      layout: even-vertical
      panes:
        - nvim
        -
  - eu-central-1:
      root: ~/git/aws-terraform/eu-central-1
      layout: even-vertical
      panes:
        - nvim
        -
        -
  - fastly:
      root: ~/git/aws-terraform/fastly
      layout: even-vertical
      panes:
        - nvim
        -
  - iam:
      root: ~/git/aws-terraform/iam
      layout: even-vertical
      panes:
        - nvim
        -
