# /Users/kforsthoevel/.config/tmuxinator/aws.yml

name: aws
root: ~/git/aws-terraform

windows:
  - eu-west-1:
      root: ~/git/aws-terraform/eu-west-1
      layout: even-vertical
      panes:
        - vim
        -
  - us-east-1:
      root: ~/git/aws-terraform/us-east-1
      layout: even-vertical
      panes:
        - vim
        -
  - eu-central-1:
      root: ~/git/aws-terraform/eu-central-1
      layout: even-vertical
      panes:
        - vim
        -
        -
  - fastly:
      root: ~/git/aws-terraform/fastly
      layout: even-vertical
      panes:
        - vim
        -
