#!/bin/sh

if [ ! -e "$HOME"/.vim/autoload/plug.vim ]; then
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u "$HOME"/.vimrc.bundles +PlugInstall +PlugClean! +qa

reset -Q

# Install tmux plugin manager
if [ ! -f "${HOME}/.tmux/plugins/tpm/README.md" ]; then
  git clone https://github.com/tmux-plugins/tpm "${HOME}/.tmux/plugins/tpm"
fi

# Install German keyboad w/ nodeadkeys
if [ ! -f "${HOME}/Library/Keyboard Layouts/German-modified.keylayout" ]; then
  cp "${HOME}/dotfiles/German-modified.keylayout" "${HOME}/Library/Keyboard Layouts/German-modified.keylayout"
fi
