[env]
  TERM = "xterm-256color"

[font]
  normal = { family = "Hack Nerd Font", style = "Regular" }
  bold = { family = "Hack Nerd Font", style = "Bold" }
  italic = { family = "Hack Nerd Font", style = "Italic" }

  size = 12.0

[window]
option_as_alt = "OnlyLeft"

[keyboard]
  bindings = [
    { key = "Space", mods = "Alt", chars = " " },
    { key = "Key5", mods = "Alt", chars = "[" },
    { key = "Key6", mods = "Alt", chars = "]" },
    { key = "Key7", mods = "Alt|Shift", chars = "\\" },
    { key = "Key7", mods = "Alt", chars = "|" },
    { key = "Key8", mods = "Alt", chars = "{" },
    { key = "Key9", mods = "Alt", chars = "}" },
    { key = 36, mods = "Command", action = "ToggleFullscreen" },
    { key = "D", mods = "Alt", chars = "\u001bd" },
    { key = "Q", mods = "Alt", chars = "\u001bq" },
  ]

[general]
import = [
  # "~/.config/alacritty/nightfox.toml",
  # "~/.config/alacritty/duskfox.toml",
  # "~/.config/alacritty/dawnfox.toml",
  # "~/.config/alacritty/dayfox.toml",
  # "~/.config/alacritty/nordfox.toml",
  "~/.config/alacritty/solarized-dark.toml",
  # "~/.config/alacritty/solarized-osaka.toml",
]
