[colors.cursor]
  text = "#002b36"
  cursor = "#93a1a1"

[colors.primary]
  background = "#002b36"
  foreground = "#93a1a1"

[colors.normal]
  black = "#002b36"
  red = "#dc322f"
  green = "#859900"
  yellow = "#b58900"
  blue = "#268bd2"
  magenta = "#6c71c4"
  cyan = "#2aa198"
  white = "#93a1a1"

[colors.bright]
  black = "#657b83"
  red = "#cb4b16"
  green = "#073642"
  yellow = "#586e75"
  blue = "#839496"
  magenta = "#eee8d5"
  cyan = "#d33682"
  white = "#fdf6e3"
